import test from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { assertOwnedContent, validateGovernance, validateOwnershipEvidence, validateOwnershipMatrix } from "../lib/governance-validation.mjs";

const release = new URL("../../releases/1.0.0/", import.meta.url), adrs = new URL("../../adrs/", import.meta.url);
test("governance validates ADR-005 and normative ownership evidence", async () => assert.deepEqual(await validateGovernance(release, adrs), { authorities: 3, placements: 66 }));
test("ownership allowlist rejects content outside an authority", async () => { const { parse } = await import("yaml"), { readFile } = await import("node:fs/promises"), matrix = parse(await readFile(new URL("conformance/ownership-matrix.yaml", release), "utf8")); assert.doesNotThrow(() => assertOwnedContent(matrix, "git", "schemas")); assert.throws(() => assertOwnedContent(matrix, "git", "provider_secrets"), /out-of-authority/i); });
test("governance CLI validates ownership and ADR together", () => { const result = spawnSync(process.execPath, [fileURLToPath(new URL("../validate.mjs", import.meta.url)), "--scope", "governance"], { encoding: "utf8" }); assert.equal(result.status, 0, result.stderr); assert.match(result.stdout, /3 authorities and 66 ownership placements/); });
test("ownership governance fails closed for every reviewer mutation", async () => { const { parse } = await import("yaml"), { readFile } = await import("node:fs/promises"), matrix = parse(await readFile(new URL("conformance/ownership-matrix.yaml", release), "utf8")), evidence = JSON.parse(await readFile(new URL("conformance/ownership-evidence.json", release), "utf8")), mutate = (value, change) => { const copy = structuredClone(value); change(copy); return copy; }; for (const invalid of [mutate(matrix, (v) => { v.raw_key = "SK-example"; }), mutate(matrix, (v) => { v.authorities.git.Authorization = "BEARER example"; }), mutate(matrix, (v) => { v.authorities.git.label = "Git ApiKey=example"; })]) assert.throws(() => validateOwnershipMatrix(invalid), /unknown|invalid/i); for (const invalid of [mutate(evidence, (v) => { v.raw_key = "SK-example"; }), mutate(evidence, (v) => { v.placements[0].Authorization = "BEARER example"; })]) assert.throws(() => validateOwnershipEvidence(matrix, invalid), /unknown/i); });
test("ownership pins exclusive normative sets and exhaustive evidence", async () => { const { parse } = await import("yaml"), { readFile } = await import("node:fs/promises"), matrix = parse(await readFile(new URL("conformance/ownership-matrix.yaml", release), "utf8")), evidence = JSON.parse(await readFile(new URL("conformance/ownership-evidence.json", release), "utf8")), mutate = (value, change) => { const copy = structuredClone(value); change(copy); return copy; }, duplicate = mutate(matrix, (v) => v.authorities.db.required.push("deployment_secrets")), transfer = mutate(matrix, (v) => { v.authorities.secret_store.required.pop(); v.authorities.db.required.push("deployment_secrets"); }); for (const invalid of [duplicate, transfer]) assert.throws(() => validateOwnershipMatrix(invalid), /normative|exclusive/i); assert.throws(() => assertOwnedContent(matrix, "db", "deployment_secrets"), /out-of-authority/i); assert.throws(() => validateOwnershipEvidence(matrix, mutate(evidence, (v) => v.placements.pop())), /exhaustive/i); });
