import test from "node:test";
import assert from "node:assert/strict";
import { assertOpenapiEquivalent } from "../lib/openapi-normalize.mjs";
const schema = { type: "object", required: ["id"], properties: { id: { type: "string" } }, additionalProperties: false };
const operation = () => ({ parameters: [{ name: "trace", in: "header", required: false, schema: { type: "string" } }], security: [{ apiKey: [] }], requestBody: { required: true, content: { "application/json": { schema } } }, responses: { 200: { description: "ok", content: { "application/json": { schema } } }, 404: { description: "missing" } } });
const spec = () => ({ openapi: "3.1.0", info: { title: "toy", version: "1.0.0" }, paths: { "/widgets": { post: operation() } }, components: { securitySchemes: { apiKey: { type: "apiKey", in: "header", name: "Authorization" } } } });
const op = (value) => value.paths["/widgets"].post, clone = () => structuredClone(spec()), move = (value, from, to) => { value[to] = value[from]; delete value[from]; };
test("semantic diff ignores representation ordering for a toy match", () => { const projected = clone(); projected.paths = { "/widgets": { post: { responses: op(projected).responses, requestBody: op(projected).requestBody, security: op(projected).security, parameters: op(projected).parameters } } }; assert.doesNotThrow(() => assertOpenapiEquivalent(spec(), projected)); });
test("semantic diff deterministically rejects every missing, extra, and drift class", () => { const cases = [
  ["path missing", (x) => delete x.paths["/widgets"]], ["path extra", (x) => x.paths["/extra"] = { get: operation() }], ["path drift", (x) => move(x.paths, "/widgets", "/widgetz")],
  ["method missing", (x) => delete x.paths["/widgets"].post], ["method extra", (x) => x.paths["/widgets"].get = operation()], ["method drift", (x) => move(x.paths["/widgets"], "post", "put")],
  ["parameter missing", (x) => op(x).parameters.pop()], ["parameter extra", (x) => op(x).parameters.push({ name: "q", in: "query", schema: { type: "string" } })], ["parameter drift", (x) => op(x).parameters[0].required = true],
  ["security missing", (x) => op(x).security = []], ["security extra", (x) => op(x).security.push({ oauth: [] })], ["security drift", (x) => x.components.securitySchemes.apiKey.type = "http"],
  ["request media missing", (x) => delete op(x).requestBody.content["application/json"]], ["request media extra", (x) => op(x).requestBody.content["text/plain"] = { schema: { type: "string" } }], ["request media drift", (x) => move(op(x).requestBody.content, "application/json", "application/xml")], ["request required drift", (x) => op(x).requestBody.required = false],
  ["request schema missing", (x) => delete op(x).requestBody.content["application/json"].schema], ["request schema extra", (x) => op(x).requestBody.content["application/json"].schema.oneOf = [{ type: "object" }]], ["request schema drift", (x) => op(x).requestBody.content["application/json"].schema.properties.id.type = "integer"],
  ["response status missing", (x) => delete op(x).responses[404]], ["response status extra", (x) => op(x).responses[201] = { description: "created" }], ["response status drift", (x) => move(op(x).responses, "200", "201")],
  ["response media missing", (x) => delete op(x).responses[200].content["application/json"]], ["response media extra", (x) => op(x).responses[200].content["text/plain"] = { schema: { type: "string" } }], ["response media drift", (x) => move(op(x).responses[200].content, "application/json", "application/xml")],
  ["response schema missing", (x) => delete op(x).responses[200].content["application/json"].schema], ["response schema extra", (x) => op(x).responses[200].content["application/json"].schema.maxProperties = 2], ["response schema drift", (x) => op(x).responses[200].content["application/json"].schema.required = []]
]; for (const [name, mutate] of cases) { const projected = clone(); mutate(projected); let first, second; assert.throws(() => assertOpenapiEquivalent(spec(), projected), (error) => (first = error.message, /semantic diff/i.test(error.message)), name); assert.throws(() => assertOpenapiEquivalent(spec(), projected), (error) => (second = error.message, true)); assert.equal(first, second, name); } });
