import test from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { access, chmod, link, mkdir, mkdtemp, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { createServer } from "node:http";
import { tmpdir } from "node:os";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { assertInvocation, parseContractSource, preflightOpenapi, readContractFile, runOpenapi } from "../lib/openapi-validation.mjs";
const tooling = fileURLToPath(new URL("../", import.meta.url)), cliFile = join(tooling, "lib/openapi-validation.mjs"), canonical = join(tooling, "test/fixtures/openapi/canonical.yaml");
const base = (body = {}) => ({ openapi: "3.1.0", info: { title: "probe", version: "1.0.0" }, paths: {}, ...body });
const api = (locator, field = "$ref") => field === "$ref" ? base({ components: { schemas: { Probe: { $ref: locator } } } }) : field === "externalValue" ? base({ paths: { "/x": { get: { responses: { 200: { description: "ok", content: { "application/json": { examples: { nested: { externalValue: locator } } } } } } } } } }) : field === "operationRef" ? base({ components: { links: { Probe: { operationRef: locator } } } }) : base({ components: { schemas: { Probe: { type: "object", discriminator: { propertyName: "kind", mapping: { probe: locator } } } } } });
const cli = (...args) => new Promise((resolve) => { const child = spawn(process.execPath, [cliFile, ...args], { encoding: "utf8" }); let stdout = "", stderr = ""; child.stdout.on("data", (value) => stdout += value); child.stderr.on("data", (value) => stderr += value); child.on("close", (status) => resolve({ status, stdout, stderr })); });
async function sandbox(run) { const root = await mkdtemp(join(tmpdir(), "openapi-policy-")); try { await run(root); } finally { await chmod(join(root, "unreadable.json"), 0o600).catch(() => {}); await rm(root, { recursive: true, force: true }); } }
test("strict local JSON/YAML parsing rejects syntax, duplicate keys, and aliases", () => { assert.throws(() => parseContractSource("{", ".json"), /parse/i); assert.throws(() => parseContractSource('{"a":1,"a":2}', ".json"), /unique|duplicate/i); assert.throws(() => parseContractSource("a: 1\na: 2", ".yaml"), /unique|duplicate/i); assert.throws(() => parseContractSource("a: &a {x: 1}\nb: *a", ".yaml"), /alias/i); });
test("recursive preflight enumerates every resolver-visible locator and terminates cycles", async () => sandbox(async (root) => { const entry = join(root, "api.json"), child = join(root, "child.json"), document = base(); document.paths["/x"] = { get: { responses: { 200: { description: "ok", content: { "application/json": { examples: { e: { externalValue: "example.json" } } } } } } } }; document.components = { schemas: { A: { $ref: "child.json" }, B: { type: "object", discriminator: { propertyName: "kind", mapping: { b: "child.json#/$defs/B" } } }, C: { $ref: "#/components/schemas/A" } }, links: { x: { operationRef: "child.json#/paths/~1x/get" } } }; await writeFile(join(root, "example.json"), "{}"); await writeFile(child, JSON.stringify({ $ref: "api.json#/components" })); await writeFile(entry, JSON.stringify(document)); const seen = await preflightOpenapi(entry, root); assert.deepEqual([...seen.keys()].map((path) => path.slice(root.length + 1)).sort(), ["api.json", "child.json", "example.json"]); }));
test("externalValue, operationRef, and discriminator mappings share the same offline policy", async () => sandbox(async (root) => { const entry = join(root, "api.json"); for (const field of ["externalValue", "operationRef", "mapping"]) { await writeFile(entry, JSON.stringify(api("https://127.0.0.1/resource", field))); await assert.rejects(preflightOpenapi(entry, root), /scheme/i, field); } }));
test("preflight rejects wrong OpenAPI and contract versions", async () => sandbox(async (root) => { const entry = join(root, "api.json"); for (const document of [{ ...base(), openapi: "3.0.3" }, { ...base(), info: { title: "probe", version: "01.0.0" } }]) { await writeFile(entry, JSON.stringify(document)); await assert.rejects(preflightOpenapi(entry, root), /OpenAPI 3\.1\.0.*SemVer/i); } }));
test("subprocess errors fail closed and remove pre-existing bundle output", async () => { const output = join(tooling, ".tmp/stale-subprocess.yaml"), error = Object.assign(new Error("spawn EPERM"), { code: "EPERM" }), runner = () => ({ status: 0, error, stdout: "", stderr: "" }); await mkdir(dirname(output), { recursive: true }); await writeFile(output, "stale"); assert.throws(() => assertInvocation(runner(), "lint"), /EPERM/); await assert.rejects(runOpenapi("bundle", canonical, output, runner), /EPERM/); await assert.rejects(access(output)); });
test("canonical control plane keeps standalone authority and explicit list semantics", async () => { const api = await readContractFile(join(tooling, "../releases/1.0.0/openapi/control-plane.yaml")), schemas = api.components.schemas; assert.equal(JSON.stringify(api).includes("../"), false); assert.equal(schemas.CredentialIssuance, undefined); assert.equal(schemas.Grant, undefined); assert.equal(api.paths["/v1/principals/{id}/credentials"].post.responses[201].content["application/json"].schema.$ref, "urn:sre-agent:schema:credential-issuance:1.0.0"); assert.equal(api.paths["/v1/grants"].post.responses[201].content["application/json"].schema.$ref, "urn:sre-agent:schema:grant:1.0.0"); assert.deepEqual(api.paths["/v1/grants"].get["x-required-query-any-of"], ["principal_id", "resource_id"]); assert.equal(api.paths["/v1/audit-events/{id}"].get.responses[200].content["application/json"].schema.$ref, "urn:sre-agent:schema:audit-event-metadata:1.0.0"); });
test("canonical Responses API is POST-only, JSON-only, and registered by name", async () => { const document = await readContractFile(join(tooling, "../releases/1.0.0/openapi/responses.yaml")), operation = document.paths["/v1/responses"].post; assert.deepEqual(Object.keys(document.paths), ["/v1/responses"]); assert.deepEqual(Object.keys(document.paths["/v1/responses"]), ["post"]); assert.equal(operation.requestBody.content["application/json"].schema.$ref, "urn:sre-agent:schema:responses-request:1.0.0"); assert.equal(operation.responses[200].content["application/json"].schema.$ref, "urn:sre-agent:schema:responses-response:1.0.0"); assert.equal(JSON.stringify(document).includes("text/event-stream"), false); const result = await cli("check", "--api", "responses"); assert.equal(result.status, 0, result.stderr); });
test("public OpenAPI lint command invokes checks for both canonical APIs", async () => { const manifest = JSON.parse(await readFile(join(tooling, "package.json"), "utf8")); assert.equal(manifest.scripts["lint:openapi"], "node lib/openapi-validation.mjs check --api control-plane && node lib/openapi-validation.mjs check --api responses"); });
test("central locator policy rejects ambiguity, escape, missing, unreadable, directory, and special targets", async () => sandbox(async (root) => {
  const entry = join(root, "api.json"), outside = join(tmpdir(), `outside-${process.pid}.json`);
  await writeFile(outside, "{}"); await mkdir(join(root, "directory")); await writeFile(join(root, "unreadable.json"), "{}"); await chmod(join(root, "unreadable.json"), 0); await symlink(outside, join(root, "escape.json")); await link(outside, join(root, "hardlink.json"));
  await new Promise((resolve, reject) => { const child = spawn("mkfifo", [join(root, "pipe")]); child.on("close", (status) => status ? reject(new Error("mkfifo failed")) : resolve()); });
  try { for (const locator of ["https://127.0.0.1/x", "//127.0.0.1/x", "file:///tmp/x", "urn:probe:x", "/etc/passwd", "../x", "../json-schema/domain/principal.schema.json", "%2e%2e/x", "%252e%252e/x", "a\\b", "a\0b", "missing.json", "unreadable.json", "directory", "pipe", "escape.json", "hardlink.json"]) {
    await writeFile(entry, JSON.stringify(api(locator)));
    await assert.rejects(preflightOpenapi(entry, root), /locator|scheme|absolute|traversal|control|backslash|missing|readable|regular|escape|hard.link/i, locator);
  } } finally { await rm(outside, { force: true }); }
}));
test("black-box preflight blocks nested externalValue network and outside sentinel reads", async () => { await mkdir(join(tooling, ".tmp"), { recursive: true }); const probe = await mkdtemp(join(tooling, ".tmp/probe-")), entry = join(probe, "api.json"), sentinel = join(tmpdir(), `sentinel-${process.pid}.json`); let requests = 0; const server = createServer((_request, response) => { requests++; response.end("{}"); }); await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve)); try { await writeFile(entry, JSON.stringify(api(`http://127.0.0.1:${server.address().port}/example`, "externalValue"))); let result = await cli("lint", entry); assert.equal(result.status, 1); assert.match(result.stderr, /scheme/i); assert.equal(requests, 0); await writeFile(sentinel, "OUTSIDE_SENTINEL"); await chmod(sentinel, 0); await writeFile(entry, JSON.stringify(api(relative(dirname(entry), sentinel)))); result = await cli("lint", entry); assert.equal(result.status, 1); assert.match(result.stderr, /traversal/i); } finally { server.close(); await chmod(sentinel, 0o600).catch(() => {}); await rm(sentinel, { force: true }); await rm(probe, { recursive: true, force: true }); } });
test("black-box bundle output cannot traverse or follow links and valid local inputs pass", async () => { const outside = join(tooling, `.bundle-sentinel-${process.pid}.yaml`), symbolic = join(tooling, ".tmp/escape.yaml"), hard = join(tooling, ".tmp/hardlink.yaml"); await writeFile(outside, "SENTINEL"); await rm(symbolic, { force: true }); await rm(hard, { force: true }); await symlink(outside, symbolic); await link(outside, hard); try { let result = await cli("bundle", canonical, join(tooling, "../escape.yaml")); assert.equal(result.status, 1); assert.match(result.stderr, /output/i); result = await cli("bundle", canonical, symbolic); assert.equal(result.status, 1); assert.match(result.stderr, /symlink/i); result = await cli("bundle", canonical, hard); assert.equal(result.status, 1); assert.match(result.stderr, /hard.link/i); result = await cli("lint", canonical); assert.equal(result.status, 0, result.stderr); } finally { await rm(symbolic, { force: true }); await rm(hard, { force: true }); await rm(outside, { force: true }); } });
test("black-box bundle stops after lint failure without writing output", async () => { const entry = join(tooling, ".tmp/invalid-openapi.json"), output = join(tooling, ".tmp/should-not-exist.yaml"); await rm(output, { force: true }); await writeFile(entry, JSON.stringify({ ...base(), paths: "invalid" })); try { const result = await cli("bundle", entry, output); assert.equal(result.status, 1); assert.match(result.stderr, /Redocly lint failed/i); await assert.rejects(access(output)); } finally { await rm(entry, { force: true }); await rm(output, { force: true }); } });
