const {test,expect}=require('/e2e/node_modules/@playwright/test');
const detail={incident_id:'inc-audit',workflow_version:'1.0.0',state:'mitigating',runs:[{run_id:'run_demo0001',current_state:'mitigating',status:'running',version:2},{run_id:'run_demo0002',current_state:'mitigating',status:'running',version:2}]};
async function auth(page,url){await page.goto(url);await page.locator('#credential-input').fill('sre_synthetic_audit_token_0001');await page.locator('#credential-form button[type=submit]').click();}
test('review conflict recovery retains reason when retrying action',async({page})=>{
 await page.route('**/api/v1/incidents/**',route=>route.request().method()==='POST'?route.fulfill({status:409,json:{error:{code:'run_conflict'}}}):route.fulfill({json:detail}));
 await auth(page,'/public/incident-ui/review.html?incident_id=inc-audit&run_id=run_demo0001');
 await page.locator('[data-command=approve_mitigation]').click();await page.locator('#decision-comment').fill('Audited reason must survive recovery');await page.locator('#decision-submit').click();await expect(page.locator('#error-409')).toBeVisible();await page.locator('#refresh-button').click();await expect(page.locator('#actions-section')).toBeVisible();await page.locator('[data-command=approve_mitigation]').click();console.log('RECOVERY reason after reopening:',JSON.stringify(await page.locator('#decision-comment').inputValue()));await page.locator('#decision-comment').scrollIntoViewIfNeeded();await page.screenshot({path:'/out/pr-416-recovery.png'});await expect(page.locator('#decision-comment')).toHaveValue('Audited reason must survive recovery');
});
test('postmortem stale response must not replace selected run',async({page})=>{
 let release;let seen;const blocked=new Promise(r=>{release=r});const started=new Promise(r=>{seen=r});let delay=false;
 await page.route('**/api/v1/incidents/**',async route=>{const u=new URL(route.request().url());if(!u.pathname.endsWith('/timeline'))return route.fulfill({json:detail});const id=u.searchParams.get('run_id');if(delay&&id==='run_demo0001'){seen();await blocked;}return route.fulfill({json:{events:[{sequence:0,summary:id+' safe record'}],has_more:false,next_cursor:'seq:0'}});});
 await auth(page,'/public/incident-ui/postmortem.html?incident_id=inc-audit');await expect(page.locator('#provenance-list')).toContainText('run_demo0002');delay=true;await page.locator('#run-select').selectOption('run_demo0001');await started;await page.locator('#run-select').selectOption('run_demo0002');await expect(page.locator('#provenance-list')).toContainText('run_demo0002');release();await page.waitForTimeout(300);console.log('RUN selector=',await page.locator('#run-select').inputValue(),'provenance=',await page.locator('#provenance-list').innerText());await page.locator('#provenance-section').scrollIntoViewIfNeeded();await page.screenshot({path:'/out/pr-418-race.png'});await expect(page.locator('#provenance-list')).not.toContainText('run_demo0001');
});
