#!/usr/bin/env python3
"""Create stable, isolated Compose settings for the current Git worktree."""

from __future__ import annotations

import argparse
import hashlib
import re
import shutil
import socket
import subprocess
from pathlib import Path

GENERATED_ENV = ".env.worktree"
PORT_KEYS = ("API_PORT", "WEB_PORT", "POSTGRES_PORT")


def repository_root() -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        check=True,
        capture_output=True,
        text=True,
    )
    return Path(result.stdout.strip()).resolve()


def worktree_identity(root: Path) -> str:
    """Use only the canonical worktree path; branches and HEAD are deliberately irrelevant."""
    return hashlib.sha256(str(root.resolve()).encode()).hexdigest()[:12]


def project_name(root: Path, identity: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", root.name.lower()).strip("-") or "sre-agent"
    return f"{slug[:36]}-wt-{identity}"


def local_bind_available(port: int) -> bool | None:
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as listener:
            listener.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 0)
            listener.bind(("127.0.0.1", port))
            return True
    except PermissionError:
        return None
    except OSError:
        return False


def docker_port_inventory(project_name: str) -> tuple[set[int], set[int]] | None:
    """Read external and same-project host ports from the Docker daemon."""
    try:
        result = subprocess.run(
            [
                "docker",
                "ps",
                "--format",
                '{{.Label "com.docker.compose.project"}}\t{{.Ports}}',
            ],
            check=True,
            capture_output=True,
            text=True,
        )
    except (FileNotFoundError, OSError, subprocess.CalledProcessError):
        return None

    external_ports: set[int] = set()
    project_ports: set[int] = set()
    for line in result.stdout.splitlines():
        project, _, published = line.partition("\t")
        ports = {int(match) for match in re.findall(r":(\d+)->", published)}
        if project == project_name:
            project_ports.update(ports)
        else:
            external_ports.update(ports)
    return external_ports, project_ports


def validate_ports(
    ports: dict[str, int],
    docker_ports: set[int] | None,
    project_ports: set[int] | None = None,
) -> bool:
    """Validate values and known collisions; return whether every check was authoritative."""
    if len(set(ports.values())) != len(ports):
        raise ValueError("API, web, and PostgreSQL ports must be different")

    fully_checked = docker_ports is not None
    for key, port in ports.items():
        if not 1 <= port <= 65535:
            raise ValueError(f"{key} must be between 1 and 65535")
        if docker_ports is not None and port in docker_ports:
            raise ValueError(f"{key}={port} is already published by another Docker container")

        locally_available = local_bind_available(port)
        if locally_available is False and port not in (project_ports or set()):
            raise ValueError(f"{key}={port} is already in use on 127.0.0.1")
        fully_checked = fully_checked and (
            locally_available is True or port in (project_ports or set())
        )
    return fully_checked


def allocate_ports(identity: str, docker_ports: set[int] | None) -> dict[str, int]:
    start = 20000 + (int(identity[:8], 16) % 10000) * 3
    for offset in range(0, 30000, 3):
        candidate = 20000 + ((start - 20000 + offset) % 30000)
        ports = dict(zip(PORT_KEYS, (candidate, candidate + 1, candidate + 2), strict=True))
        if docker_ports is not None and any(port in docker_ports for port in ports.values()):
            continue
        if all(local_bind_available(port) is not False for port in ports.values()):
            return ports
    raise RuntimeError("No free local port block found")


def read_environment(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, value = line.split("=", 1)
            values[key] = value
    return values


def render_environment(identity: str, name: str, ports: dict[str, int]) -> str:
    return "\n".join(
        [
            "# Generated by scripts/bootstrap-worktree.py; safe to recreate.",
            f"WORKTREE_ID={identity}",
            f"COMPOSE_PROJECT_NAME={name}",
            *(f"{key}={ports[key]}" for key in PORT_KEYS),
            "",
        ]
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--api-port", type=int)
    parser.add_argument("--web-port", type=int)
    parser.add_argument("--db-port", "--postgres-port", dest="postgres_port", type=int)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = repository_root()
    example = root / ".env.example"
    local_env = root / ".env"
    generated_env = root / GENERATED_ENV
    identity = worktree_identity(root)
    name = project_name(root, identity)
    inventory = docker_port_inventory(name)
    published_ports = inventory[0] if inventory is not None else None
    project_ports = inventory[1] if inventory is not None else None

    if not local_env.exists():
        shutil.copyfile(example, local_env)
        print("Created .env from .env.example")

    requested = {
        "API_PORT": args.api_port,
        "WEB_PORT": args.web_port,
        "POSTGRES_PORT": args.postgres_port,
    }
    has_override = any(value is not None for value in requested.values())

    if generated_env.exists() and not has_override:
        existing = read_environment(generated_env)
        if existing.get("WORKTREE_ID") != identity:
            raise SystemExit(
                ".env.worktree belongs to another worktree; remove it and rerun bootstrap"
            )
        if not all(existing.get(key, "").isdigit() for key in PORT_KEYS):
            raise SystemExit(".env.worktree is invalid; remove it and rerun bootstrap")
        existing_name = existing.get("COMPOSE_PROJECT_NAME", "")
        if not re.fullmatch(r"[a-z0-9][a-z0-9_-]*", existing_name):
            raise SystemExit(".env.worktree is invalid; remove it and rerun bootstrap")
        ports = {key: int(existing[key]) for key in PORT_KEYS}
        try:
            fully_checked = validate_ports(ports, published_ports, project_ports)
        except ValueError as error:
            raise SystemExit(f"Invalid .env.worktree: {error}") from error
        print(f"Reusing {existing_name} from .env.worktree")
        print_port_check_status(fully_checked, ports)
        return 0

    if generated_env.exists():
        existing = read_environment(generated_env)
        if existing.get("WORKTREE_ID") != identity:
            raise SystemExit(
                ".env.worktree belongs to another worktree; remove it and rerun bootstrap"
            )
        ports = {key: int(existing[key]) for key in PORT_KEYS}
    else:
        ports = allocate_ports(identity, published_ports)

    for key, value in requested.items():
        if value is not None:
            ports[key] = value
    try:
        fully_checked = validate_ports(ports, published_ports, project_ports)
    except ValueError as error:
        raise SystemExit(f"Cannot configure worktree ports: {error}") from error

    generated_env.write_text(render_environment(identity, name, ports))
    print(f"Configured {name} in .env.worktree")
    print_port_check_status(fully_checked, ports)
    print("Run: scripts/worktree-compose up --build --wait")
    return 0


def print_port_check_status(fully_checked: bool, ports: dict[str, int]) -> None:
    if fully_checked:
        return
    print(
        "Warning: this sandbox could not prove that every non-Docker host port is free. "
        "docker compose up --wait is the fail-closed authority."
    )
    suggested_api = ports["API_PORT"] + 100
    if suggested_api > 65533:
        suggested_api = 20000
    print(
        "If Compose reports a port collision, choose three free ports and run: "
        "scripts/bootstrap-worktree.py "
        f"--api-port {suggested_api} --web-port {suggested_api + 1} "
        f"--db-port {suggested_api + 2}"
    )


if __name__ == "__main__":
    raise SystemExit(main())
